package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

type contextKey string

// userInfo groups authenticated user identity fields under a single context
// key, avoiding context pollution from multiple keys for related data.
type userInfo struct {
	ID       string
	Username string
	Role     string
}

const userInfoKey contextKey = "user_info"

// Claims matches GeminiMCP's JWT claims structure exactly so tokens are
// interoperable: a token generated by GeminiMCP with the same secret key
// will pass validation here.
type Claims struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	Role     string `json:"role"`
	jwt.RegisteredClaims
}

// extractTokenFromHeader extracts a Bearer token from an Authorization header.
// Uses strings.Fields for robust whitespace handling (mirrors GeminiMCP).
func extractTokenFromHeader(authHeader string) string {
	parts := strings.Fields(authHeader)
	if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") {
		return ""
	}
	return parts[1]
}

// validateJWT validates a JWT token using the same parameters as GeminiMCP:
//   - Algorithm pinned to HS256 (prevents algorithm-confusion attacks)
//   - Issuer:   "gemini-mcp"
//   - Audience: "gemini-mcp-user"
//   - Leeway:   60 seconds (clock-skew tolerance)
func validateJWT(secretKey []byte, tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(token *jwt.Token) (interface{}, error) {
		if token.Method != jwt.SigningMethodHS256 {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return secretKey, nil
	},
		jwt.WithIssuer("gemini-mcp"),
		jwt.WithAudience("gemini-mcp-user"),
		jwt.WithLeeway(60*time.Second),
	)
	if err != nil {
		return nil, err
	}
	if claims, ok := token.Claims.(*Claims); ok && token.Valid {
		return claims, nil
	}
	return nil, fmt.Errorf("invalid token")
}

// newAuthHTTPMiddleware returns an http.Handler that validates JWT Bearer tokens
// at the HTTP transport layer — before any MCP handshake or initialization
// takes place. An invalid or missing token yields an immediate HTTP 401 with a
// WWW-Authenticate header; the MCP handler is never reached.
//
// On a valid token the handler enriches the request context with a userInfo
// struct (under userInfoKey) so tool handlers can log the caller's identity.
func newAuthHTTPMiddleware(secretKey []byte, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		authHeader := r.Header.Get("Authorization")
		tokenString := extractTokenFromHeader(authHeader)

		var (
			claims  *Claims
			authErr string
		)

		switch {
		case tokenString == "" && authHeader == "":
			authErr = "missing_token"
		case tokenString == "":
			authErr = "invalid_token"
		default:
			var err error
			claims, err = validateJWT(secretKey, tokenString)
			if err != nil {
				switch {
				case errors.Is(err, jwt.ErrTokenExpired):
					authErr = "expired_token"
				case errors.Is(err, jwt.ErrTokenNotValidYet):
					authErr = "token_not_valid_yet"
				case errors.Is(err, jwt.ErrTokenMalformed):
					authErr = "malformed_token"
				case errors.Is(err, jwt.ErrTokenSignatureInvalid):
					authErr = "invalid_signature"
				default:
					authErr = "invalid_token"
				}
			}
		}

		if authErr != "" {
			w.Header().Set("Content-Type", "application/json")
			w.Header().Set("WWW-Authenticate", `Bearer realm="mcp"`)
			w.WriteHeader(http.StatusUnauthorized)
			fmt.Fprintf(w, `{"error":"authentication required","detail":"%s"}`, authErr) //nolint:errcheck // best-effort error response
			return
		}

		// Valid token — enrich context with user identity for handler logging.
		ctx := context.WithValue(r.Context(), userInfoKey, userInfo{
			ID:       claims.UserID,
			Username: claims.Username,
			Role:     claims.Role,
		})
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// getUserInfo extracts user identity fields from the request context.
// Returns empty strings when the context carries no identity (e.g. stdio).
func getUserInfo(ctx context.Context) (userID, username string) {
	if info, ok := ctx.Value(userInfoKey).(userInfo); ok {
		return info.ID, info.Username
	}
	return "", ""
}
