package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/mark3labs/mcp-go/server"
)

// HTTP server timeouts to mitigate Slowloris-style DoS attacks.
const (
	httpReadTimeout  = 30 * time.Second
	httpWriteTimeout = 15 * time.Minute // must accommodate the longest web-search (timeoutXHigh = 15m)
	httpIdleTimeout  = 120 * time.Second
)

// RunStdioTransport runs the MCP server using STDIO transport.
func RunStdioTransport(mcpServer *server.MCPServer) error {
	Info("transport listening", "protocol", "stdio")
	return server.ServeStdio(mcpServer)
}

// RunHTTPTransport runs the MCP server using Streamable HTTP transport.
//
// The MCP handler is mounted at "/" (catch-all) so the server works behind
// reverse proxies that forward the original request URI (e.g. nginx with
// variable proxy_pass sends /answer/mcp, not /mcp). The mcp-go
// StreamableHTTPServer routes by HTTP method, not path, so a catch-all
// mount is safe and correct.
//
// When cfg.AuthEnabled is true, the MCP handler is wrapped with
// newAuthHTTPMiddleware which validates the JWT Bearer token at the HTTP layer
// and returns HTTP 401 before any MCP handshake occurs. Tokens generated by
// GeminiMCP with the same secret key are accepted without modification.
//
// When cfg.Heartbeat > 0 the server sends periodic SSE heartbeat pings on
// streaming connections — important for long-running web-search requests that
// would otherwise be silently dropped by proxies or load balancers.
func RunHTTPTransport(mcpServer *server.MCPServer, cfg MCPConfig) error {
	var mcpOpts []server.StreamableHTTPOption

	if cfg.Heartbeat > 0 {
		Debug("heartbeat configured", "interval", cfg.Heartbeat)
		mcpOpts = append(mcpOpts, server.WithHeartbeatInterval(cfg.Heartbeat))
	}

	// Disable DNS rebinding protection — the server runs on remote hosts
	// behind reverse proxies, not on localhost. Controlled by config;
	// defaults to true (protection off) since production deployments
	// always sit behind nginx.
	if cfg.DisableLocalhostProtection {
		mcpOpts = append(mcpOpts, server.WithDisableLocalhostProtection(true))
	}

	mcpOpts = append(mcpOpts, server.WithStreamableHTTPLogger(SLogger()))

	mcpHandler := server.NewStreamableHTTPServer(mcpServer, mcpOpts...)

	// Optionally wrap with auth middleware for a real HTTP 401 before MCP init.
	var handler http.Handler = mcpHandler
	if cfg.AuthEnabled {
		Info("auth enabled", "method", "JWT/HS256")
		handler = newAuthHTTPMiddleware([]byte(cfg.AuthSecretKey), mcpHandler)
	}

	mux := http.NewServeMux()
	mux.Handle("/", handler)

	addr := fmt.Sprintf("%s:%s", cfg.Host, cfg.Port)
	Info("transport listening", "protocol", "http", "addr", addr, "endpoint", fmt.Sprintf("http://%s/", addr))

	srv := &http.Server{
		Addr:         addr,
		Handler:      mux,
		ReadTimeout:  httpReadTimeout,
		WriteTimeout: httpWriteTimeout,
		IdleTimeout:  httpIdleTimeout,
	}
	return srv.ListenAndServe()
}
